### ISSUE TITLE
[BUG] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fourstepper** [external-secrets/external-secrets#1093]
This happened during upgrade in one of our environments from `0.5.1` to `0.5.2`

Upon reverting to `0.5.1`, everything returned back to normal

```
│ {"level":"info","ts":1651834452.3383605,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}                             │
│ {"level":"info","ts":1651834452.3389316,"logger":"setup","msg":"starting manager"}                                                                                     │
│ {"level":"info","ts":1651834452.3393881,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":":8080"}                                                     │
│ {"level":"info","ts":1651834452.339616,"logger":"controller.secretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"Secr │
│ {"level":"info","ts":1651834452.3398552,"logger":"controller.secretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"Secr │
│ {"level":"info","ts":1651834452.3399162,"logger":"controller.clustersecretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kin │
│ {"level":"info","ts":1651834452.3400044,"logger":"controller.clustersecretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind │
│ {"level":"info","ts":1651834452.3396783,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":" │
│ {"level":"info","ts":1651834452.3400652,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":" │
│ {"level":"info","ts":1651834452.3401313,"logger":"controller.externalsecret","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"E │
│ {"level":"info","ts":1651834452.3401906,"logger":"controller.clusterexternalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler  │
│ {"level":"info","ts":1651834452.3402438,"logger":"controller.clusterexternalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler  │
│ {"level":"info","ts":1651834452.3402889,"logger":"controller.clusterexternalsecret","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler k │
│ {"level":"info","ts":1651834452.440813,"logger":"controller.secretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"SecretSt │
│ {"level":"info","ts":1651834452.4409208,"logger":"controller.clustersecretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":" │
│ {"level":"info","ts":1651834452.4423451,"logger":"controller.clusterexternalsecret","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind │
│ {"level":"info","ts":1651834452.5423884,"logger":"controller.externalsecret","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"Exte │
│ panic: runtime error: invalid memory address or nil pointer dereference                                                                                                │
│ [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e93119]                                                                                               │
│                                                                                                                                                                        │
│ goroutine 547 [running]:                                                                                                                                               │
│ github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).readSecret(0xc001c2a8c0, {0x33f2bc0, 0xc001b36cf0}, {0xc0006ab900, 0xc001c0cb28}, {0x0, 0x0} │
│     /home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:642 +0x199                                                                         │
│ github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).GetSecret(0x1, {0x33f2bc0, 0xc001b36cf0}, {{0xc0006ab900, 0x37}, {0x0, 0x0}, {0x0, 0x0}, {0x │
│     /home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:484 +0x5e                                                                          │
│ github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).GetSecretMap(0xc001b36cf0, {0x33f2bc0, 0xc001b36cf0}, {{0xc0006ab900, 0x37}, {0x0, 0x0}, {0x │
│     /home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:516 +0x71                                                                          │
│ github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc00121f260, {0x33f2bc0, 0xc001b36cf0}, {0x3412298, 0 │
│     /home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:540 +0x42d                                         │
│ github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc00121f260, {0x33f2bc0, 0xc001b36cf0}, {{{0xc000ad7060, 0x10}, { │
│     /home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:233 +0xdc6                                         │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0010e4e70, {0x33f2bc0, 0xc001b36c60}, {{{0xc000ad7060, 0x2ca7200}, {0xc000ce70b0, 0x │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f                                                    │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0010e4e70, {0x33f2b18, 0xc0014a0900}, {0x29a2000, 0xc000662020})              │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e                                                    │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0010e4e70, {0x33f2b18, 0xc0014a0900})                                      │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205                                                    │
│ sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                                   │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85                                                     │
│ created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2                                                                            │
│     /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357  
```

**Comment by moolen** [comment]
That was fixed in https://github.com/external-secrets/external-secrets/pull/1074 i suppose

**Comment by fourstepper** [comment]
that is possibly the cause, thanks :)

**Comment by moolen** [comment]
Checked the stacktrace: `pkg/provider/vault/vault.go:642`. It definitely was fixed. I'll close this and look that we'll release this asap.

**Comment by fourstepper** [comment]
Thanks, appreciated :)
