### ISSUE TITLE
ExternalSecret crash using vault provider if external secret key does not exist on vault side

### ISSUE THREAD

**Issue by mick1627** [external-secrets/external-secrets#1126]
external secret version : v0.5.2
provider: hashicorp vault
Issue : if  key defined in ExternalSecret is not present in hashicorp vault, external secret crash.

ExternalSecret exemple :  

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo
  namespace: argocd
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
    - extract:
        key: argocd/argocd-repo
````

if key is not in vault, external secret crash with this error message :

```log
sg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","worker count":10}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e93119]

goroutine 472 [running]:
github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).readSecret(0xc00133f040, {0x33f2bc0, 0xc0012d8630}, {0xc0018270e0, 0xc002090b28}, {0x0, 0x0})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:642 +0x199
github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).GetSecret(0x1, {0x33f2bc0, 0xc0012d8630}, {{0xc0018270e0, 0x21}, {0x0, 0x0}, {0x0, 0x0}, {0xc0006d3929, ...}})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:484 +0x5e
github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).GetSecretMap(0xc0012d8630, {0x33f2bc0, 0xc0012d8630}, {{0xc0018270e0, 0x21}, {0x0, 0x0}, {0x0, 0x0}, {0xc0006d3929, ...}})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:516 +0x71
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc000ca2420, {0x33f2bc0, 0xc0012d8630}, {0x3412298, 0xc00133f040}, 0xc00003f800)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:540 +0x42d
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc000ca2420, {0x33f2bc0, 0xc0012d8630}, {{{0xc0006d3916, 0x6}, {0xc001836ba0, 0x1a}}})
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:233 +0xdc6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00118cdc0, {0x33f2bc0, 0xc0012d85a0}, {{{0xc0006d3916, 0x2ca7200}, {0xc001836ba0, 0x413c74}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00118cdc0, {0x33f2b18, 0xc000ef3a00}, {0x29a2000, 0xc000150540})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00118cdc0, {0x33f2b18, 0xc000ef3a00})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357
```

This should only trigger an error message in external secret log file.

**Comment by moolen** [comment]
That was fixed recently, we'll do a release later today. Thanks for reporting!

**Comment by knelasevero** [comment]
Closing this one due to the release :) Feel free to re-open in case this still happens
