### ISSUE TITLE
SIGSEGV when running version 0.5.2. Working as intended in 0.5.1

### ISSUE THREAD

**Issue by lollek** [external-secrets/external-secrets#1133]
**Describe the solution you'd like**
I recently set up external-secrets for version 0.5.2 against Hashicorp Vault, but when I attempt to fetch a secret from Vault to Kubernetes the application simply dies, and keeps dying until crash loop backoff. If there is no secret to fetch in the path, or if policy access is denied, it works as intended (i.e. it doesn't work), but when configured correctly it crashes. After downgrading to version 0.5.1 it works as intended.

**What is the added value?**
-

**Give us examples of the outcome**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1e93119]
 
goroutine 270 [running]:
github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).readSecret(0xc0012e3d60, {0x33f2bc0, 0xc0015f41e0}, {0xc001720900, 0x0}, {0x0, 0x0})
/home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:642 +0x199
github.com/external-secrets/external-secrets/pkg/provider/vault.(*client).GetSecret(0xc0015f41e0, {0x33f2bc0, 0xc0015f41e0}, {{0xc001720900, 0x10}, {0x0, 0x0}, {0xc001720910, 0x4}, {0xc0017208f8, ...}})
/home/runner/work/external-secrets/external-secrets/pkg/provider/vault/vault.go:484 +0x5e
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc000a199e0, {0x33f2bc0, 0xc0015f41e0}, {0x3412298, 0xc0012e3d60}, 0xc000da5600)
/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:558 +0x154
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc000a199e0, {0x33f2bc0, 0xc0015f41e0}, {{{0xc001720100, 0xb}, {0xc0017200f0, 0xd}}})
/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:233 +0xdc6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000b326e0, {0x33f2bc0, 0xc0015f4150}, {{{0xc001720100, 0x2ca7200}, {0xc0017200f0, 0x413c74}}})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000b326e0, {0x33f2b18, 0xc000a16d00}, {0x29a2000, 0xc0005b4320})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000b326e0, {0x33f2b18, 0xc000a16d00})
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x357
```

**Observations (Constraints, Context, etc):**

- I tried a few different authentication methods, but it did not have any effect. 
- I'm using a key-value v2 secrets engine
- I experience the error with the base values.yaml for the relevant helm chart version, where the only modifications are securityContext and using an image with a modified ca-certificates.crt to allow for a self-signed cert.

**Comment by moolen** [comment]
That was fixed in 0.5.3 / #1074 That happened when a secret does not exist. Can you try to upgrade to see if that fixes your issue :pray: ? 

Feel free to reopen if you have any further issues.
