### ISSUE TITLE
Bug: process crash loop due to "panic: assignment to entry in nil map"

### ISSUE THREAD

**Issue by fluffysquirrels** [external-secrets/external-secrets#1271]
In one of our Kubernetes clusters we had an externalsecrets object that caused the external-secrets process to crash over and over again. Deleting the externalsecrets object fixed the issue temporarily. Re-deploying the same externalsecrets object with Helmsman did not reproduce the issue.

**Describe the solution you'd like**
Reconciling secrets that cause the fault should not crash the process, but log an error.

**What is the added value?**
The process will not crash and will continue to work on other secrets with lower CPU usage and not triggering alerts.

**Give us examples of the outcome**

Log messages like:
```
externalsecrets object "foo" is invalid due to xyz, skipping.
```

**Observations (Constraints, Context, etc):**

We are using your chart version v0.4.4, which uses application version v0.4.4 from Docker, which means the map assignment that caused the error is here: https://github.com/external-secrets/external-secrets/blob/v0.4.4/pkg/template/v2/template.go#L72

Kubernetes version 1.20 running in AWS EKS. external-secrets is configured to point at the AWS Systems Manager Parameter Store.

Here is the stack trace from our logs:

```
panic: assignment to entry in nil map

goroutine 349 [running]:
github.com/external-secrets/external-secrets/pkg/template/v2.Execute(0x31bb828, 0xc000be5890, 0xc0003412c0)
	/home/runner/work/external-secrets/external-secrets/pkg/template/v2/template.go:72 +0x125
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).applyTemplate(0xc000783b60, {0x319ae80, 0xc0017778c0}, 0xc0039d8d20, 0xc0003412c0, 0xc0019b5380)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_template.go:63 +0x3aa
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile.func3()
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:221 +0x1ca
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc0003412c0, {{0xc002ebb3f0, 0xc0017778c0}, {0xc002ecac78, 0x100004316419108}}, {0x3217158, 0xc0003412c0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x319ae80, 0xc0017778c0}, {0x31de960, 0xc000a64640}, {0x3217158, 0xc0003412c0}, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/controller/controllerutil/controllerutil.go:211 +0x250
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc000783b60, {0x319ae80, 0xc0017778c0}, {{{0xc002ebb3f0, 0xb}, {0xc002ecac00, 0x13}}})
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:237 +0xeca
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000f38bb0, {0x319ae80, 0xc001777830}, {{{0xc002ebb3f0, 0x2ae2c40}, {0xc002ecac00, 0x413c54}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000f38bb0, {0x319add8, 0xc000657540}, {0x282c9c0, 0xc000e30d20})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000f38bb0, {0x319add8, 0xc000657540})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357
```

Here is a redacted view from `kubectl describe` of the failing externalsecrets object before it was deleted:
```
k describe externalsecret foo-bar
Name:         foo-bar
Namespace:    foo-ns
Labels:       app.kubernetes.io/instance=foo
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/version=git-<REDACTED HASH>
              helm.sh/chart=my-chart-1.2.3
Annotations:  argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded,HookFailed
              helm.sh/hook: pre-install,pre-upgrade
              helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
              helm.sh/hook-weight: -1
API Version:  external-secrets.io/v1alpha1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2022-06-10T15:49:25Z
  Generation:          1
  Managed Fields:
    API Version:  external-secrets.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:argocd.argoproj.io/hook-delete-policy:
          f:helm.sh/hook:
          f:helm.sh/hook-delete-policy:
          f:helm.sh/hook-weight:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/managed-by:
          f:app.kubernetes.io/version:
          f:helm.sh/chart:
      f:spec:
        .:
        f:data:
        f:refreshInterval:
        f:secretStoreRef:
          .:
          f:kind:
          f:name:
        f:target:
          .:
          f:creationPolicy:
          f:name:
          f:template:
            .:
            f:data:
              .:
              f:ENV_1:
              f:ENV_2:
              f:ENV_3:
              f:ENV_4:
              f:ENV_5:
              f:ENV_6:
            f:engineVersion:
            f:metadata:
              .:
              f:annotations:
                .:
                f:reloader.stakater.com/match:
              f:labels:
                .:
                f:app.kubernetes.io/instance:
                f:app.kubernetes.io/managed-by:
                f:app.kubernetes.io/version:
                f:helm.sh/chart:
    Manager:         Go-http-client
    Operation:       Update
    Time:            2022-06-10T15:49:25Z
  Resource Version:  1633293998
  UID:               <Redacted UUID>
Spec:
  Data:
    Remote Ref:
      Key:       ENV_1
    Secret Key:  ENV_1
    Remote Ref:
      Key:       ENV_5
    Secret Key:  ENV_5
    Remote Ref:
      Key:       ENV_2
    Secret Key:  ENV_2_JSON
    Remote Ref:
      Key:       ENV_4
    Secret Key:  ENV_4_JSON
    Remote Ref:
      Key:           ENV_3
    Secret Key:      ENV_3_JSON
  Refresh Interval:  0m
  Secret Store Ref:
    Kind:  ClusterSecretStore
    Name:  default
  Target:
    Creation Policy:  Owner
    Name:             foo-hooks
    Template:
      Data:
        ENV_1:  {{ .ENV_1 }}
        ENV_2:  {{ get (mustFromJson .ENV_2_JSON) "param2" }}
        ENV_3:  {{ get (mustFromJson .ENV_3_JSON) "param3" }}
        ENV_4:  {{ get (mustFromJson .ENV_4_JSON) "param4" }}
        ENV_5:  {{ .ENV_5 }}
        ENV_6:  {{ get (mustFromJson .ENV_4_JSON) "param6" }}
      Engine Version:                  v2
      Metadata:
        Annotations:
          reloader.stakater.com/match:  true
        Labels:
          app.kubernetes.io/instance:    foo
          app.kubernetes.io/managed-by:  Helm
          app.kubernetes.io/version:     git-<REDACTED HASH>
          helm.sh/chart:                 my-chart-1.2.3
Events:                                  <none>
```

**Comment by gusfcarvalho** [comment]
Hi @fluffysquirrels! this has already been addressed in newer ESO releases!

**Comment by fluffysquirrels** [comment]
Great news! I'll close this task then and schedule the upgrade. Thanks!

**Comment by nazarewk** [comment]
FYI: duplicate of #936 :)
