### ISSUE TITLE
Error: certificate signature failure

### ISSUE THREAD

**Issue by yelhouti** [external-secrets/external-secrets#2178]
I have been using `external-secrets` in k8s for a year and it works great. However to night external secrets started failing:
> ERROR,"Error: certificate signature failure".

After checking the logs I found:
```json
{"level":50,"message_time":"2023-03-28T03:36:56.391Z","pid":18,"hostname":"kubernetes-external-secrets-6bbd8f97d8-59q85","payload":{"err":{"type":"RequestError","message":"Error: certificate signature failure","stack":"RequestError: Error: certificate signature failure\n    at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.emit (domain.js:475:12)\n    at Request.onRequestError (/app/node_modules/request/request.js:877:8)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)","name":"RequestError","cause":{"type":"Error","message":"certificate signature failure","stack":"Error: certificate signature failure\n    at TLSWrap.verifyError (<anonymous>)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","code":"CERT_SIGNATURE_FAILURE"},"error":{"type":"Error","message":"certificate signature failure","stack":"Error: certificate signature failure\n    at TLSWrap.verifyError (<anonymous>)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","code":"CERT_SIGNATURE_FAILURE"},"options":{"json":{"role":"default","jwt":"[Redacted]"},"resolveWithFullResponse":true,"simple":false,"strictSSL":true,"followAllRedirects":true,"method":"POST","path":"/auth/kubernetes/login","headers":"[Redacted]","uri":"https://vault.vault.svc.cluster.local:8200/v1/auth/kubernetes/login","transform2xxOnly":false}}},"msg":"failure while polling the secret jx-staging/keycloak-postgresql"}
```
restarting the pod fixed the problem.

Is there a way to fix this please ? As far as I can tell the app is not able to talk to the vault due to a certificate issue (certificate expired ? ) but the vault certificate seems fine and works after a restart. Could it be a cache issue of the certificate ?

**Comment by moolen** [comment]
Hey, you're using kubernetes-external-secrets. That has been deprecated and does not receive any further updates.
