### ISSUE TITLE
Empty String in data[].remoteRef.key in ExternalSecret when using the GitLab Provider crashses controller

### ISSUE THREAD

**Issue by yvjessestephens** [external-secrets/external-secrets#3474]
**Describe the bug**
We are using the gitlab provider SecretStore to pull CICD variables from GitLab into K8s Secrets. When we accidentally left data[].remoteRef.key as "", the controller crashed (i.e. the external-secrets pods went into a crash/restart cycle) with an error, "invalid memory address or nil pointer dereference." We didn't realize this for a few weeks until someone reported their cicd variables were not syncing at which time we noticed the controller pods had been continuously restarting.

I was not able to reproduce the issue with the fake provider, so I think it specifically an issue with the gitlab provider.

Stack Trace and preceeding logs:
```
2024-05-09T14:44:10-05:00 {"level":"info","ts":1715283850.2760806,"logger":"provider.vault","msg":"initializing vault cache","size":262144}
2024-05-09T14:44:10-05:00 {"level":"info","ts":1715283850.276135,"logger":"setup","msg":"starting manager"}
2024-05-09T14:44:10-05:00 {"level":"info","ts":1715283850.2765207,"logger":"controller-runtime.metrics","msg":"Starting metrics server"}
2024-05-09T14:44:10-05:00 I0509 19:44:10.276703       1 leaderelection.go:250] attempting to acquire leader lease external-secrets/external-secrets-controller...
2024-05-09T14:44:10-05:00 {"level":"info","ts":1715283850.2770212,"logger":"controller-runtime.metrics","msg":"Serving metrics server","bindAddress":":9102","secure":false}
2024-05-09T14:44:26-05:00 I0509 19:44:26.698839       1 leaderelection.go:260] successfully acquired lease external-secrets/external-secrets-controller
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8323407,"msg":"Starting EventSource","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","source":"kind source: *v1alpha1.PushSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.844212,"msg":"Starting EventSource","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","source":"kind source: *v1beta1.SecretStore"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8323426,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1beta1.ClusterExternalSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8455257,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1beta1.ExternalSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.845546,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1.Namespace"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.845552,"msg":"Starting Controller","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8442974,"msg":"Starting Controller","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.829943,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1beta1.ExternalSecret"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.844353,"msg":"Starting Controller","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8462386,"msg":"Starting EventSource","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","source":"kind source: *v1beta1.ClusterSecretStore"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8462791,"msg":"Starting Controller","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.846946,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1.PartialObjectMetadata"}
2024-05-09T14:44:26-05:00 {"level":"info","ts":1715283866.8469913,"msg":"Starting Controller","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret"}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.1979568,"msg":"Starting workers","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","worker count":1}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.2044928,"msg":"Starting workers","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","worker count":1}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.2047784,"msg":"Starting workers","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","worker count":1}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.2048256,"msg":"Starting workers","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","worker count":1}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.2048185,"msg":"Starting workers","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","worker count":1}
2024-05-09T14:44:27-05:00 {"level":"info","ts":1715283867.8741221,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"gitlab-ci-vars","namespace":"default"},"namespace":"default","name":"gitlab-ci-vars","reconcileID":"62ee22d5-bf54-438b-9f52-d63f6071a7a8"}
2024-05-09T14:44:27-05:00 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2024-05-09T14:44:27-05:00 	panic: runtime error: invalid memory address or nil pointer dereference
2024-05-09T14:44:27-05:00 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x23ddf6d]
2024-05-09T14:44:27-05:00 
2024-05-09T14:44:27-05:00 goroutine 87655 [running]:
2024-05-09T14:44:27-05:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:116 +0x1e5
2024-05-09T14:44:27-05:00 panic({0x347a100?, 0x707d8e0?})
2024-05-09T14:44:27-05:00 	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x21f
2024-05-09T14:44:27-05:00 github.com/external-secrets/external-secrets/pkg/provider/gitlab.(*gitlabBase).GetSecret(0xc00035d8f0, {0x3b1a4e0?, 0x48?}, {{0x0, 0x0}, {0xc001555d30, 0x4}, {0x0, 0x0}, {0x0, ...}, ...})
2024-05-09T14:44:27-05:00 	/home/runner/work/external-secrets/external-secrets/pkg/provider/gitlab/gitlab.go:253 +0x64d
2024-05-09T14:44:27-05:00 github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).handleSecretData(_, {_, _}, _, {{{0x2f818fd, 0xe}, {0xc0021b07c0, 0x1b}}, {{0xc001555ce0, 0xe}, ...}, ...}, ...)
2024-05-09T14:44:27-05:00 	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:96 +0x108
2024-05-09T14:44:27-05:00 github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc000361490, {0x4549aa0?, 0xc0021f2540}, 0xc00238a800)
2024-05-09T14:44:27-05:00 	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:78 +0x63e
2024-05-09T14:44:27-05:00 github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc000361490, {0x4549aa0?, 0xc0021f2540}, {{{0xc001555cf0, 0x7}, {0xc001555ce0, 0xe}}})
2024-05-09T14:44:27-05:00 	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:207 +0x12c9
2024-05-09T14:44:27-05:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x454e7c0?, {0x4549aa0?, 0xc0021f2540?}, {{{0xc001555cf0?, 0xb?}, {0xc001555ce0?, 0x0?}}})
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:119 +0xb7
2024-05-09T14:44:27-05:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000f7adc0, {0x4549ad8, 0xc000f75c70}, {0x36f8ba0?, 0xc00071cf80?})
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:316 +0x3cc
2024-05-09T14:44:27-05:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000f7adc0, {0x4549ad8, 0xc000f75c70})
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:266 +0x1af
2024-05-09T14:44:27-05:00 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227 +0x79
2024-05-09T14:44:27-05:00 created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 87486
2024-05-09T14:44:27-05:00 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:223 +0x565
```

**To Reproduce**
Steps to reproduce the behavior (a real gitlab access token, url, group id, and cicd variable name will be need to be added into these manifests):
1. provide all relevant manifests
cluster-secret-store.yaml (holds secret for accessing GitLab API. Will require a real gitlab access token to be specified)
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab-vars-cluster-secret-store
spec:
  provider:
    fake:
      data:
      - key: youversion-group-eso-access-token
        value: <gitlab access token>
        version: v1
```

gitlab-token-external-secret.yaml (relies on the ClusterSecretStore above.)
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-vars-cluster-secret-store
  target:
    name: gitlab-access-token # name of the k8s secret to be created.
    creationPolicy: Owner
  data:
    - secretKey: token # Key given to the secret to be created on the cluster, will be used in the gitlab-secret-store
      remoteRef: 
        key: youversion-group-eso-access-token # name of the secret in gitlab-vars-cluster-secret-store
        version: v1
```

gitlab-external-secret.yaml (relies on the ExternalSecret above. Will require a real url and group id to be specified):
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    gitlab:
      url: <gitlab url>
      auth:
        SecretRef:
          accessToken:
            name: gitlab-access-token
            key: token
      groupIDs: ["<gitlab group id>"]
```

target-external-secret.yaml (specifies which GitLab CICD variable to put into a K8s Secret. Will require a real gitlab cicd variable name)
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-ci-vars
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store
  target:
    name: gitlab-ci-vars # Name of the secret to be created on the cluster
    creationPolicy: Owner
  data:
    - secretKey: VAR_1
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: <gitlab cicd variable name> # Key of the variable on Gitlab
    # - secretKey: VAR_2
    #   remoteRef:
    #     conversionStrategy: Default
    #     decodingStrategy: None
    #     key: "" # <----- this is what causes the controller to crash
```

3. provide the Kubernetes and ESO version
We use the helm chart to deploy version 0.9.13

**Expected behavior**
I expect the controller to log an error rather than go into a crash and restart loop, so that other exiting ExternalSecrets that are properly configured can continue to be sync'd. The fake provider handles this case and logs the following:
`"error retrieving secret at .data[0], key: , err: Secret does not exist`
The full log appears as follows:
```
2024-05-09T14:26:32-05:00 {"level":"error","ts":1715282792.6705892,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"example-for-bug-reproduction","namespace":"default"},"namespace":"default","name":"example-for-bug-reproduction","reconcileID":"b2b32f6f-375f-48d2-8097-595fa72863e1","error":"error retrieving secret at .data[0], key: , err: Secret does not exist","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.1/pkg/internal/controller/controller.go:227"}
```

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Skarlso** [comment]
@yvjessestephens Hello 👋 

Is this still a thing? :D

**Comment by yvjessestephens** [comment]
@Skarlso it is still an issue on version 0.10.0. I ran a test with the steps described above and got this:
```
{"level":"info","ts":1724765496.2968984,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"gitlab-ci-vars","namespace":"faktoryloadtest"},"namespace":"faktoryloadtest","name":"gitlab-ci-vars","reconcileID":"936db2ed-c70a-4351-9180-721b869c1354"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x26a80b3]

goroutine 30385 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x375cb20?, 0x78c1380?})
	/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/panic.go:770 +0x132
github.com/external-secrets/external-secrets/pkg/provider/gitlab.(*gitlabBase).GetSecret(0xc0007ce380, {0xc000f80008?, 0xc001df3350?}, {{0x0, 0x0}, {0xc001fc3e4c, 0x4}, {0x0, 0x0}, {0x0, ...}, ...})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/gitlab/gitlab.go:243 +0x433
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).handleSecretData(_, {_, _}, _, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc001fc3df0, 0xe}, ...}, ...}, ...)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:97 +0x108
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc0003d9420, {0x4a277b8, 0xc001df2240}, 0xc000d0f800)
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:79 +0x61e
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc0003d9420, {0x4a277b8, 0xc001df2240}, {{{0xc001fc3bb0, 0xf}, {0xc001fc3ba0, 0xe}}})
	/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:224 +0x1396
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x4a2ded8?, {0x4a277b8?, 0xc001df2240?}, {{{0xc001fc3bb0?, 0xb?}, {0xc001fc3ba0?, 0x0?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000ee60b0, {0x4a277f0, 0xc000abb3b0}, {0x3a020e0, 0xc0001512c0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000ee60b0, {0x4a277f0, 0xc000abb3b0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 30134
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:218 +0x486
```

**Comment by Skarlso** [comment]
Nice, thanks. I'll investigate it.

**Comment by Skarlso** [comment]
Not stale, just didn't have the time.
